---
- hosts: dgset-1
  become: true
  tasks:
    - name: Copy plugin
      copy:
        backup: true
        dest: /usr/lib/nagios/plugins/
        mode: "0755"
        src: /tmp/check_debian_packages
    - name: Copy deb file
      copy:
        backup: true
        dest: /etc/apt/
        src: /tmp/sources.list
    - name: Schedule package update
      cron:
        backup: true
        hour: "6"
        job: "apt-get update"
        minute: "0"
        name: "package update"
